### ISSUE TITLE
Massive error that does not allow anki to open

### ISSUE THREAD

**Issue by silentcicada1** [ijgnd/anki__when_is_next_learning_card_due_today_due#1]
I have localized the error below to this add on with Mac 10.15.1 and anki 2.1.23:

Anki was unable to open your collection file. If problems persist after restarting your computer, please use the Open Backup button in the profile manager.

Debug info:
Traceback (most recent call last):
  File "aqt/main.py", line 441, in loadCollection
  File "aqt/main.py", line 467, in _loadCollection
  File "aqt/main.py", line 588, in moveToState
  File "aqt/main.py", line 595, in _deckBrowserState
  File "/Users/papasmurf/Library/Application Support/Anki2/addons21/699175524/__init__.py", line 44, in wrapped
    orig(*args, **kwargs)
  File "</Applications/Anki 2.1.23.app/Contents/MacOS/decorator.pyc:decorator-gen-162>", line 2, in show
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 657, in repl
  File "aqt/deckbrowser.py", line 54, in show
  File "aqt/deckbrowser.py", line 110, in _renderPage
  File "aqt/deckbrowser.py", line 117, in __renderPage
  File "</Applications/Anki 2.1.23.app/Contents/MacOS/decorator.pyc:decorator-gen-232>", line 2, in _renderStats
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 663, in repl
  File "/Users/papasmurf/Library/Application Support/Anki2/addons21/review_heatmap/views.py", line 90, in deckbrowserRenderStats
    ret = _old(self)
  File "</Applications/Anki 2.1.23.app/Contents/MacOS/decorator.pyc:decorator-gen-208>", line 2, in _renderStats
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 663, in repl
  File "/Users/papasmurf/Library/Application Support/Anki2/addons21/SIC Just time left (no deck stats)/mds_time_left.py", line 78, in renderStats
    + _old(self) + "<br>" \
  File "</Applications/Anki 2.1.23.app/Contents/MacOS/decorator.pyc:decorator-gen-154>", line 2, in _renderStats
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 663, in repl
  File "/Users/papasmurf/Library/Application Support/Anki2/addons21/563204849/__init__.py", line 64, in deckbrowserMessage
    if whenIsNextLrnDue():
  File "/Users/papasmurf/Library/Application Support/Anki2/addons21/563204849/__init__.py", line 39, in whenIsNextLrnDue
    todaystart = datetime.datetime(year=now.year, month=now.month,
ValueError: day is out of range for month

**Comment by loganbeach** [comment]
I just had the same error and was also able to localize it to "when is next learning card due today"
It happened just after midnight on April first which is maybe what error was?

**Comment by ijgnd** [comment]
Thank you very much for reporting this bug. The problem can only occur on the first of a month. So you should be able to restart Anki today. I changed the code to something hopefully more robust. Could you update and let me know if you run into problems.

**Comment by loganbeach** [comment]
Yeah for sure :)

Logan Beach

**Comment by silentcicada1** [comment]
Will do thank you
